#!/bin/csh

source $HOME/.login
source $HOME/.cshrc

# Setup environment.
if (${?ARCH}) then
   if ($ARCH == SGI) then
      set MAKE = `which gmake`
      set MAIL = /usr/sbin/mailx
   else if ($ARCH == athlon) then
      set MAKE = `which make`
      set MAIL = /bin/mail
   else if ($ARCH == ix86 ) then
      set MAKE = `which make`
      set MAIL = /bin/mail
   else
      echo "Unsupported architecture, exiting..."
      exit
   endif
   echo "ARCH = " $ARCH
else
   echo "ARCH is not set, exiting..."
   exit
endif

set TMP_DIR = $HOME/.build_test_dir
echo "TMP_DIR = " $TMP_DIR

if !(${?TMP_DIR}) then
   echo $TMP_DIR "does not exist, exiting..."
   exit
endif

if (-e $TMP_DIR/BUILD_FAILED) then
   set TMP_DIR = $HOME/.testdriver_dir
else if (-e $HOME/.build_test_dir/BUILD_FAILED) then
   set TMP_DIR = $HOME/.build_test_dir/BUILD_FAILED
endif


if (-e $TMP_DIR/BUILD_FAILED) then
   if (-e $TMP_DIR/cron_log_mailing_list) then
      set cron_log_mailing_list = `cat $TMP_DIR/cron_log_mailing_list`
   else set cron_log_mailing_list = "hans-johnson@uiowa.edu"
   endif

   # Preprocess the log file.
   grep -A 15 -B 15 "Error" $TMP_DIR/BUILD_FAILED > $TMP_DIR/BUILD_FAILED.out

   $MAIL -s "`hostname -s`: purify cron log" $cron_log_mailing_list < $TMP_DIR/BUILD_FAILED.out
   rm -f $TMP_DIR/BUILD_FAILED
   rm -f $TMP_DIR/BUILD_FAILED.out
endif 
