/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    $RCSfile: itkStatisticsHeaderTest.cxx,v $
  Language:  C++
  Date:      $Date: 2007/02/24 17:53:01 $
  Version:   $Revision: 1.1 $

  Copyright (c) Insight Software Consortium. All rights reserved.
  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/

#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkListSample.h"
#include "itkHistogram.h"
#include "itkListSampleToHistogramFilter.h"
#include "itkHistogramToTextureFeaturesFilter.h"
#include "itkSample.h"
#include "itkSampleClassifierFilter.h"
#include "itkSampleToSubsampleFilter.h"
#include "itkSubsample.h"
#include "itkMeanFilter.h"
#include "itkMembershipSample.h"
#include "itkNeighborhoodSampler.h"
#include "itkCovarianceFilter.h"
#include "itkWeightedMeanFilter.h"
#include "itkWeightedCovarianceFilter.h"
#include "itkImageToListSampleFilter.h"
#include "itkScalarImageToCooccurrenceMatrixFilter.h"
#include "itkScalarImageToCooccurrenceListSampleFilter.h"
#include "itkImageToListSampleAdaptor.h"
#include "itkPointSetToListSampleAdaptor.h"
#include "itkJointDomainImageToListSampleAdaptor.h"
#include "itkDenseFrequencyContainer.h"
#include "itkSparseFrequencyContainer.h"
#include "itkScalarImageToTextureFeaturesFilter.h"
#include "itkMembershipFunctionBase.h"
#include "itkDistanceMetric.h"
#include "itkEuclideanDistanceMetric.h"
#include "itkEuclideanSquareDistanceMetric.h"
#include "itkMahalanobisDistanceMetric.h"
#include "itkManhattanDistanceMetric.h"
#include "itkDecisionRule.h"
#include "itkMaximumDecisionRule2.h"
#include "itkMinimumDecisionRule2.h"
#include "itkDistanceToCentroidMembershipFunction.h"
#include "itkGaussianMembershipFunction.h"


int main ( int , char*  )
{
  return EXIT_SUCCESS;
}
