<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
  ProjectType="Visual C++"
  Version="7.10"
  Name="INSTALL"
  SccProjectName=""
  SccLocalPath=""
  Keyword="Win32Proj">
  <Platforms>
    <Platform
      Name="Win32"/>
  </Platforms>
  <Configurations>
    <Configuration
      Name="Debug|Win32"
      OutputDirectory="Debug"
      IntermediateDirectory="INSTALL.dir\Debug"
      ConfigurationType="10"
      UseOfMFC="0"
      ATLMinimizesCRunTimeLibraryUsage="FALSE"
      CharacterSet="2">
      <Tool
        Name="VCCLCompilerTool"
        AdditionalOptions=" -DCMAKE_INTDIR=\&quot;Debug\&quot;"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        ExceptionHandling="FALSE"
        WarningLevel="3"
        PreprocessorDefinitions=""
        AssemblerListingLocation="Debug"
        ObjectFile="$(IntDir)\"
/>
      <Tool
        Name="VCCustomBuildTool"/>
      <Tool
        Name="VCResourceCompilerTool"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        PreprocessorDefinitions="" />
      <Tool
        Name="VCMIDLTool"
        PreprocessorDefinitions=""
        MkTypLibCompatible="FALSE"
        TargetEnvironment="1"
        GenerateStublessProxies="TRUE"
        TypeLibraryName="$(InputName).tlb"
        OutputDirectory="$(IntDir)"
        HeaderFileName="$(InputName).h"
        DLLDataFileName=""
        InterfaceIdentifierFileName="$(InputName)_i.c"
        ProxyFileName="$(InputName)_p.c"/>
      <Tool
        Name="VCPreBuildEventTool"/>
      <Tool
        Name="VCPreLinkEventTool"/>
      <Tool
        Name="VCPostBuildEventTool"
CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -DBUILD_TYPE=$(OutDir) -P cmake_install.cmake&#x0D;&#x0A;"/>
    </Configuration>
    <Configuration
      Name="RelWithDebInfo|Win32"
      OutputDirectory="RelWithDebInfo"
      IntermediateDirectory="INSTALL.dir\RelWithDebInfo"
      ConfigurationType="10"
      UseOfMFC="0"
      ATLMinimizesCRunTimeLibraryUsage="FALSE"
      CharacterSet="2">
      <Tool
        Name="VCCLCompilerTool"
        AdditionalOptions=" -DCMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        ExceptionHandling="FALSE"
        WarningLevel="3"
        PreprocessorDefinitions=""
        AssemblerListingLocation="RelWithDebInfo"
        ObjectFile="$(IntDir)\"
/>
      <Tool
        Name="VCCustomBuildTool"/>
      <Tool
        Name="VCResourceCompilerTool"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        PreprocessorDefinitions="" />
      <Tool
        Name="VCMIDLTool"
        PreprocessorDefinitions=""
        MkTypLibCompatible="FALSE"
        TargetEnvironment="1"
        GenerateStublessProxies="TRUE"
        TypeLibraryName="$(InputName).tlb"
        OutputDirectory="$(IntDir)"
        HeaderFileName="$(InputName).h"
        DLLDataFileName=""
        InterfaceIdentifierFileName="$(InputName)_i.c"
        ProxyFileName="$(InputName)_p.c"/>
      <Tool
        Name="VCPreBuildEventTool"/>
      <Tool
        Name="VCPreLinkEventTool"/>
      <Tool
        Name="VCPostBuildEventTool"
CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -DBUILD_TYPE=$(OutDir) -P cmake_install.cmake&#x0D;&#x0A;"/>
    </Configuration>
    <Configuration
      Name="Release|Win32"
      OutputDirectory="Release"
      IntermediateDirectory="INSTALL.dir\Release"
      ConfigurationType="10"
      UseOfMFC="0"
      ATLMinimizesCRunTimeLibraryUsage="FALSE"
      CharacterSet="2">
      <Tool
        Name="VCCLCompilerTool"
        AdditionalOptions=" -DCMAKE_INTDIR=\&quot;Release\&quot;"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        ExceptionHandling="FALSE"
        WarningLevel="3"
        PreprocessorDefinitions=""
        AssemblerListingLocation="Release"
        ObjectFile="$(IntDir)\"
/>
      <Tool
        Name="VCCustomBuildTool"/>
      <Tool
        Name="VCResourceCompilerTool"
        AdditionalIncludeDirectories="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Hybrid;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Patented;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Rendering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\IO;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Imaging;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Graphics;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Filtering;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Common\Testing\Cxx;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\zlib;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\jpeg;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\png;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\tiff;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\expat;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\Utilities\DICOMParser;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\Utilities\DICOMParser;D:\research\EXTERN~1\slicer2\Lib\win32\tcl-build\include;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\cxx;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32;"
        PreprocessorDefinitions="" />
      <Tool
        Name="VCMIDLTool"
        PreprocessorDefinitions=""
        MkTypLibCompatible="FALSE"
        TargetEnvironment="1"
        GenerateStublessProxies="TRUE"
        TypeLibraryName="$(InputName).tlb"
        OutputDirectory="$(IntDir)"
        HeaderFileName="$(InputName).h"
        DLLDataFileName=""
        InterfaceIdentifierFileName="$(InputName)_i.c"
        ProxyFileName="$(InputName)_p.c"/>
      <Tool
        Name="VCPreBuildEventTool"/>
      <Tool
        Name="VCPreLinkEventTool"/>
      <Tool
        Name="VCPostBuildEventTool"
CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -DBUILD_TYPE=$(OutDir) -P cmake_install.cmake&#x0D;&#x0A;"/>
    </Configuration>
  </Configurations>
  <Files>
      <File
        RelativePath="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt">
        <FileConfiguration
          Name="Debug|Win32">
          <Tool
          Name="VCCustomBuildTool"
          Description="Building Custom Rule D:/research/ExternalPackages/slicer2/Modules/vtkRuleBasedSegmentation/CMakeLists.txt"
          CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -HD:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation -Bd:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32&#x0D;&#x0A;"
          AdditionalDependencies="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeVS71FindMake.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystem.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystemSpecificInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeGenericSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\gcc.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.c.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCPlatform.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXPlatform.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeOptions.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\FindVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKConfig.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKLibraryDepends.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\UseVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeImportBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\CMake\vtkLoadCMakeExtensions.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\vtkRuleBasedSegmentationConfigure.h.cin;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Templates\CMakeWindowsSystemConfig.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;"
          Outputs="INSTALL.vcproj.cmake"/>
        </FileConfiguration>
        <FileConfiguration
          Name="RelWithDebInfo|Win32">
          <Tool
          Name="VCCustomBuildTool"
          Description="Building Custom Rule D:/research/ExternalPackages/slicer2/Modules/vtkRuleBasedSegmentation/CMakeLists.txt"
          CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -HD:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation -Bd:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32&#x0D;&#x0A;"
          AdditionalDependencies="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeVS71FindMake.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystem.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystemSpecificInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeGenericSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\gcc.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.c.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCPlatform.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXPlatform.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeOptions.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\FindVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKConfig.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKLibraryDepends.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\UseVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeImportBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\CMake\vtkLoadCMakeExtensions.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\vtkRuleBasedSegmentationConfigure.h.cin;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Templates\CMakeWindowsSystemConfig.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;"
          Outputs="INSTALL.vcproj.cmake"/>
        </FileConfiguration>
        <FileConfiguration
          Name="Release|Win32">
          <Tool
          Name="VCCustomBuildTool"
          Description="Building Custom Rule D:/research/ExternalPackages/slicer2/Modules/vtkRuleBasedSegmentation/CMakeLists.txt"
          CommandLine="D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\bin\cmake.exe -HD:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation -Bd:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32&#x0D;&#x0A;"
          AdditionalDependencies="D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeVS71FindMake.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystem.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeSystemSpecificInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeGenericSystem.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\gcc.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeDetermineRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCCompiler.cmake.in;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeRCInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestRCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCCompiler.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CheckTypeSize.c.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCCompiler.cmake.in;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCXXInformation.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\Windows-cl.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCPlatform.cmake;d:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\builds\win32\CMakeFiles\CMakeCXXPlatform.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\Platform\WindowsPaths.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeCommonLanguageInclude.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeTestCXXCompiler.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeOptions.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\FindVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKConfig.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKLibraryDepends.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\UseVTK.cmake;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Modules\CMakeImportBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK-build\VTKBuildSettings.cmake;d:\research\ExternalPackages\slicer2\Lib\win32\VTK\CMake\vtkLoadCMakeExtensions.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\vtkRuleBasedSegmentationConfigure.h.cin;D:\research\ExternalPackages\slicer2\Lib\win32\CMake-build\share\CMake\Templates\CMakeWindowsSystemConfig.cmake;D:\research\ExternalPackages\slicer2\Modules\vtkRuleBasedSegmentation\CMakeLists.txt;"
          Outputs="INSTALL.vcproj.cmake"/>
        </FileConfiguration>
      </File>
  </Files>
  <Globals>
  </Globals>
</VisualStudioProject>
