#
# This module is provided as CURL_USE_FILE by CURLConfig.cmake.  
# It can be INCLUDEd in a project to load the needed compiler and linker
# settings to use CURL:
#   FIND_PACKAGE(CURL REQUIRED)
#   INCLUDE(${CURL_USE_FILE})
#

IF(NOT CURL_USE_FILE_INCLUDED)
  SET(CURL_USE_FILE_INCLUDED 1)

  # Load the compiler settings used for CURL.
  #IF(CURL_BUILD_SETTINGS_FILE)
    #INCLUDE(${CMAKE_ROOT}/Modules/CMakeImportBuildSettings.cmake)
    #CMAKE_IMPORT_BUILD_SETTINGS(${CURL_BUILD_SETTINGS_FILE})
  #ENDIF(CURL_BUILD_SETTINGS_FILE)

  # Add compiler flags needed to use CURL.
  #SET(CMAKE_C_FLAGS 
    #"${CMAKE_C_FLAGS} ${CURL_REQUIRED_C_FLAGS}")
  #SET(CMAKE_CXX_FLAGS 
    #"${CMAKE_CXX_FLAGS} ${CURL_REQUIRED_CXX_FLAGS}")
  #SET(CMAKE_EXE_LINKER_FLAGS 
    #"${CMAKE_EXE_LINKER_FLAGS} ${CURL_REQUIRED_EXE_LINKER_FLAGS}")
  #SET(CMAKE_SHARED_LINKER_FLAGS 
    #"${CMAKE_SHARED_LINKER_FLAGS} ${CURL_REQUIRED_SHARED_LINKER_FLAGS}")
  #SET(CMAKE_MODULE_LINKER_FLAGS 
    #"${CMAKE_MODULE_LINKER_FLAGS} ${CURL_REQUIRED_MODULE_LINKER_FLAGS}")

  # Add include directories needed to use CURL.
  INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIRS})

  # Add link directories needed to use CURL.
  LINK_DIRECTORIES(${CURL_LIBRARY_DIRS})

  #ADD_DEFINITIONS(-DHAVE_CONFIG_H)

  # Add cmake module path.
  #SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CURL_CMAKE_DIR}")

ENDIF(NOT CURL_USE_FILE_INCLUDED)
