// This file was automatically generated by:
//  /projects/prostate/elhawary/Slicer3-build/bin/GenerateLM --InputTxt /projects/prostate/elhawary/SlicerModules/HybridNav/HybridNav/HybridNav.txt --OutputHeader /projects/prostate/elhawary/SlicerModules/HybridNav/HybridNav-build/HybridNavLib.h --OutputCxx /projects/prostate/elhawary/SlicerModules/HybridNav/HybridNav-build/HybridNavLib.cxx
#include "HybridNavLib.h"

#include "vtkHybridNavLogic.h"
#include "vtkHybridNavGUI.h"

extern "C" {
Module_EXPORT char HybridNavModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<loadable>\n"
"  <name>HybridNav</name>\n"
"  <shortname>HybridNav</shortname>\n"
"  <guiname>HybridNav</guiname>\n"
"  <tclinitname>Hybridnav_Init</tclinitname>\n"
"  <message>Initializing HybridNav Module...</message>\n"
"</loadable>\n"
"\n"
;
}

char*
GetLoadableModuleDescription()
{
  return HybridNavModuleDescription;
}

void*
GetLoadableModuleGUI()
{
  return vtkHybridNavGUI::New ( );
}


void*
GetLoadableModuleLogic()
{
  return vtkHybridNavLogic::New ( );
}
