mv vtkSlicerFixedPointRayCastImage.h vtkSlicerFixedPointRayCastImage2.h
mv vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.cxx vtkSlicerFixedPointVolumeRayCastCompositeGOHelper2.cxx     
mv vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.h vtkSlicerFixedPointVolumeRayCastCompositeGOHelper2.h 
mv vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.cxx vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper2.cxx
mv vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.h vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper2.h 
mv vtkSlicerFixedPointVolumeRayCastCompositeHelper.cxx vtkSlicerFixedPointVolumeRayCastCompositeHelper2.cxx
mv vtkSlicerFixedPointVolumeRayCastCompositeHelper.h vtkSlicerFixedPointVolumeRayCastCompositeHelper2.h
mv vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.cxx vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper2.cxx
mv vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.h vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper2.h    
mv vtkSlicerFixedPointVolumeRayCastHelper.cxx vtkSlicerFixedPointVolumeRayCastHelper2.cxx
mv vtkSlicerFixedPointVolumeRayCastHelper.h   vtkSlicerFixedPointVolumeRayCastHelper2.h
mv vtkSlicerFixedPointVolumeRayCastMIPHelper.cxx vtkSlicerFixedPointVolumeRayCastMIPHelper2.cxx
mv vtkSlicerFixedPointVolumeRayCastMIPHelper.h vtkSlicerFixedPointVolumeRayCastMIPHelper2.h
mv vtkSlicerFixedPointVolumeRayCastMapper.cxx vtkSlicerFixedPointVolumeRayCastMapper2.cxx
mv vtkSlicerFixedPointVolumeRayCastMapper.h   vtkSlicerFixedPointVolumeRayCastMapper2.h
mv vtkSlicerGPURayCastVolumeMapper.cxx   vtkSlicerGPURayCastVolumeMapper2.cxx               
mv vtkSlicerGPURayCastVolumeMapper.h vtkSlicerGPURayCastVolumeMapper2.h               
mv vtkSlicerGPURayCastVolumeTextureMapper3D.cxx   vtkSlicerGPURayCastVolumeTextureMapper3D2.cxx         
mv vtkSlicerGPURayCastVolumeTextureMapper3D.h vtkSlicerGPURayCastVolumeTextureMapper3D2.h            
mv vtkSlicerGPUVolumeMapper.cxx   vtkSlicerGPUVolumeMapper2.cxx               
mv vtkSlicerGPUVolumeMapper.h vtkSlicerGPUVolumeMapper2.h                  
mv vtkSlicerGPUVolumeTextureMapper3D.cxx vtkSlicerGPUVolumeTextureMapper3D2.cxx            
mv vtkSlicerGPUVolumeTextureMapper3D.h vtkSlicerGPUVolumeTextureMapper3D2.h               
mv vtkSlicerMesaRayCastImageDisplayHelper.cxx vtkSlicerMesaRayCastImageDisplayHelper2.cxx            
mv vtkSlicerMesaRayCastImageDisplayHelper.h vtkSlicerMesaRayCastImageDisplayHelper2.h            
mv vtkSlicerOpenGLRayCastImageDisplayHelper.cxx   vtkSlicerOpenGLRayCastImageDisplayHelper2.cxx         
mv vtkSlicerOpenGLRayCastImageDisplayHelper.h vtkSlicerOpenGLRayCastImageDisplayHelper2.h            
mv vtkSlicerOpenGLVolumeTextureMapper3D.cxx   vtkSlicerOpenGLVolumeTextureMapper3D2.cxx            
mv vtkSlicerOpenGLVolumeTextureMapper3D.h vtkSlicerOpenGLVolumeTextureMapper3D2.h            
mv vtkSlicerRayCastImageDisplayHelper.cxx vtkSlicerRayCastImageDisplayHelper2.cxx            
mv vtkSlicerRayCastImageDisplayHelper.h   vtkSlicerRayCastImageDisplayHelper2.h            
mv vtkSlicerVolumePropertyWidget.cxx vtkSlicerVolumePropertyWidget2.cxx               
mv vtkSlicerVolumePropertyWidget.h   vtkSlicerVolumePropertyWidget2.h               
mv vtkSlicerVolumeRenderingFactory.cxx   vtkSlicerVolumeRenderingFactory2.cxx               
mv vtkSlicerVolumeRenderingFactory.h vtkSlicerVolumeRenderingFactory2.h               
mv vtkSlicerVolumeTextureMapper3D.cxx vtkSlicerVolumeTextureMapper3D2.cxx               
mv vtkSlicerVolumeTextureMapper3D.h   vtkSlicerVolumeTextureMapper3D2.h               
mv vtkVolumeRenderingReplacements.h   vtkVolumeRenderingReplacements2.h               
mv vtkVolumeRenderingReplacements2Configure.h.in vtkVolumeRenderingReplacements2Configure.h.in         
mv vtkVolumeRenderingReplacementsWin32Header.h vtkVolumeRenderingReplacements2Win32Header.h               

