#!/bin/bash

# http://www.na-mic.org/Wiki/index.php/Engineering:SandBox#Tabs_in_the_source_file
# Not sure why this is needed...


if [ "$1" != "" ]; then
 echo Removing tabs and Windows end-lines from $1
 sed -i -e 's/\t/  /g' $1
 dos2unix $1
 exit 0
else
 echo "Usage: sanitize <filename>"
 exit 1
fi
