#pragma warning(disable:4786)
#pragma warning(disable:4503)
#pragma warning(disable:4244)
// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <sovFlVTKDisplay.h>
#include "AttrVisualizer.h"
#include <FL/Fl_Input.H>
#include <FL/Fl_Round_Button.H>

class gui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Button *btnOK;
private:
  inline void cb_btnOK_i(Fl_Button*, void*);
  static void cb_btnOK(Fl_Button*, void*);
public:
  sov::FlVTKDisplay *m_sovDisplay;
private:
  AttrVisualizer *m_Visualization;
public:
  Fl_Input *edtFilename;
  Fl_Round_Button *rdMesh;
private:
  inline void cb_rdMesh_i(Fl_Round_Button*, void*);
  static void cb_rdMesh(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *rdAttribute;
private:
  inline void cb_rdAttribute_i(Fl_Round_Button*, void*);
  static void cb_rdAttribute(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *rdLoad;
private:
  inline void cb_rdLoad_i(Fl_Round_Button*, void*);
  static void cb_rdLoad(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *rdSave;
private:
  inline void cb_rdSave_i(Fl_Round_Button*, void*);
  static void cb_rdSave(Fl_Round_Button*, void*);
public:
  void show(int argc, char **argv);
};
#endif
