FIND_PATH(WFDIRECTINTERFACE_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/src/interfaces/direct/WFDirectInterface.h)

FIND_LIBRARY(WFDIRECTINTERFACE_LIBRARY NAMES wfdirectinterface PATH ${CMAKE_SOURCE_DIR}/bin /usr/lib /usr/local/lib) 

IF (WFDIRECTINTERFACE_INCLUDE_DIR)
   SET(WFDIRECTINTERFACE_FOUND TRUE)
ENDIF (WFDIRECTINTERFACE_INCLUDE_DIR)


IF (WFDIRECTINTERFACE_FOUND)
   IF (NOT WFDIRECTINTERFACE_FIND_QUIETLY)
      MESSAGE(STATUS "Found WFDirectInterface: ${WFDIRECTINTERFACE_LIBRARY}")
   ENDIF (NOT WFDIRECTINTERFACE_FIND_QUIETLY)
ELSE (WFDIRECTINTERFACE_FOUND)
   IF (WFDIRECTINTERFACE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find WFDirectInterface-lib")
   ENDIF (WFDIRECTINTERFACE_FIND_REQUIRED)
ENDIF (WFDIRECTINTERFACE_FOUND)
