REM Remember the home directory to return there after script completion
set HOME_DIR=%CD%


:case01
REM ---------------------------------------------------------
SET CASENO=01
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case02
REM ---------------------------------------------------------
SET CASENO=02
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case03
REM ---------------------------------------------------------
SET CASENO=03
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case04
REM ---------------------------------------------------------
SET CASENO=04
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case05
REM ---------------------------------------------------------
SET CASENO=05
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case06
REM ---------------------------------------------------------
SET CASENO=06
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case07
REM ---------------------------------------------------------
SET CASENO=07
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case08
REM ---------------------------------------------------------
SET CASENO=08
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case09
REM ---------------------------------------------------------
SET CASENO=09
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case10
REM ---------------------------------------------------------
SET CASENO=10
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case11
REM ---------------------------------------------------------
SET CASENO=11
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case12
REM ---------------------------------------------------------
SET CASENO=12
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case13
REM ---------------------------------------------------------
SET CASENO=13
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case14
REM ---------------------------------------------------------
SET CASENO=14
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case15
REM ---------------------------------------------------------
SET CASENO=15
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case16
REM ---------------------------------------------------------
SET CASENO=16
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case17
REM ---------------------------------------------------------
SET CASENO=17
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case18
REM ---------------------------------------------------------
SET CASENO=18
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case19
REM ---------------------------------------------------------
SET CASENO=19
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case20
REM ---------------------------------------------------------
SET CASENO=20
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case21
REM ---------------------------------------------------------
SET CASENO=21
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case22
REM ---------------------------------------------------------
SET CASENO=22
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case23
REM ---------------------------------------------------------
SET CASENO=23
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case24
REM ---------------------------------------------------------
SET CASENO=24
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case25
REM ---------------------------------------------------------
SET CASENO=25
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case26
REM ---------------------------------------------------------
SET CASENO=26
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case27
REM ---------------------------------------------------------
SET CASENO=27
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case28
REM ---------------------------------------------------------
SET CASENO=28
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case29
REM ---------------------------------------------------------
SET CASENO=29
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------

:case30
REM ---------------------------------------------------------
SET CASENO=30
chdir /d %RESULT_DATA_DIR%\%CASENO%
REM Registration without volumetric mask
%SLICE_REG_EXE% --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_RoiFullVolume.mha --resampledRigidMovingImage ComputedRigidVolume_RoiFullVolume.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_RoiFullVolume.mha --defFieldImage ComputedDefField_RoiFullVolume.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_RoiFullVolume.mha --metricTestOutputRotation MetricTestOutputRotation_RoiFullVolume.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_RoiFullVolume.mha --deformationDifferenceVector=DefFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=DefFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_RoiFullVolume.mha --deformationDifferenceVector=RigidFieldDiff_RoiFullVolume.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_RoiFullVolume.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM Registration with larg 3-plane mask
%SLICE_REG_EXE% --volumeImageMask %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOpSeg-Roi3sPRPB.mha --volumeImage DeformImage-B2_IntraOp.mha --sliceImage %INPUT_DATA_DIR%/DefRegEvalSampleData/B2_PreOp.mha --rigidFieldImage ComputedRigidField_Roi3sPRPB.mha --resampledRigidMovingImage ComputedRigidVolume_Roi3sPRPB.mha --deformable --gridSpacing 30 --maxDeformation 10 --resampledDefMovingImage ComputedDefVolume_Roi3sPRPB.mha --defFieldImage ComputedDefField_Roi3sPRPB.mha --metricTesting  --metricTestTranslationRange -20,20,-20,20,-10,10 --metricTestTranslationResolution 31,31,3 --metricTestRotationRange -15,15,-15,15,-5,5 --metricTestRotationResolution 31,31,3 --metricTestOutputTranslation MetricTestOutputTranslation_Roi3sPRPB.mha --metricTestOutputRotation MetricTestOutputRotation_Roi3sPRPB.mha
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedDefField_Roi3sPRPB.mha --deformationDifferenceVector=DefFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=DefFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha 
%EVAL_REG_ERROR_EXE% --deformationReference=DeformImage-B2_IntraOpDefField.mha --deformationComputed=ComputedRigidField_Roi3sPRPB.mha --deformationDifferenceVector=RigidFieldDiff_Roi3sPRPB.mha --deformationDifferenceMagnitude=RigidFieldDiffMag_Roi3sPRPB.mha --mask=DeformImage-B2_IntraOpSeg.mha
REM ---------------------------------------------------------


:end
chdir /d %HOME_DIR%
