import os
import sys
import string

import datetime


segExe = "src/r/SFLSRobustStat3DTestProbMap"

if len(sys.argv) < 3:
    print "args: targetT2Image atlasImage(probability map generated by atlasBasedSeg.py)"
    sys.exit(-1)


targetT2Image = sys.argv[1]
atlasImage = sys.argv[2]


# generate results dir
now = datetime.datetime.now()
rsltDirPrefix = os.path.basename(targetT2Image)
rsltDirPrefix = rsltDirPrefix.replace(".nrrd", "");
rsltDir = rsltDirPrefix + "-" + str(now.year) + "-" + str(now.month) + "-" + str(now.day) + "-" + str(now.hour)
if os.path.exists(rsltDir):
    rsltDir += ("-" + str(now.minute))
cmd = "mkdir " + rsltDir
os.system(cmd)
#print cmd


for numIter in [1500, 2500]:
    for curvatureWeight in [0.6, 0.8, 0.9]:
        for homogeniety in [0.6, 0.8, 0.9]:

            outputName = targetT2Image.replace(".nrrd", "-finalSeg");
            outputName = outputName + '-' + str(numIter) + '-' + str(homogeniety) + '-' + str(curvatureWeight) + '.nrrd'
            outputName = os.path.basename(outputName)
            outputName = os.path.join(rsltDir, outputName)
    
            segCmd = " ".join([segExe, targetT2Image, atlasImage, outputName, str(numIter), str(homogeniety), str(curvatureWeight)])
            os.system(segCmd)
