FIND_PATH(ASIO_INCLUDE_DIR asio.hpp /usr/include /usr/local/include)

#FIND_LIBRARY(ASIO_LIBRARY NAMES asio PATH /usr/lib /usr/local/lib) 

IF (ASIO_INCLUDE_DIR)
   SET(ASIO_FOUND TRUE)
ENDIF (ASIO_INCLUDE_DIR)


IF (ASIO_FOUND)
   IF (NOT ASIO_FIND_QUIETLY)
      MESSAGE(STATUS "Found ASIO: ${ASIO_INCLUDE_DIR}")
   ENDIF (NOT ASIO_FIND_QUIETLY)
ELSE (ASIO_FOUND)
   IF (ASIO_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Asio-lib")
   ENDIF (ASIO_FIND_REQUIRED)
ENDIF (ASIO_FOUND)
