// This file was automatically generated by:
//  /home/freak/Slicer3-build/bin/GenerateLM --InputTxt /home/freak/Slicer3/Modules/NeuroEndoscopicNavigation/NeuroEndoscopicNavigation.txt --OutputHeader /home/freak/Slicer3/Modules/NeuroEndoscopicNavigation/NeuroEndoscopicNavigationLib.h --OutputCxx /home/freak/Slicer3/Modules/NeuroEndoscopicNavigation/NeuroEndoscopicNavigationLib.cxx
#include "NeuroEndoscopicNavigationLib.h"

#include "vtkNeuroEndoscopicNavigationLogic.h"
#include "vtkNeuroEndoscopicNavigationGUI.h"

extern "C" {
Module_EXPORT char NeuroEndoscopicNavigationModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<loadable>\n"
"  <name>NeuroEndoscopic Navigation</name>\n"
"  <shortname>NeuroEndoscopicNavigation</shortname>\n"
"  <guiname>NeuroEndoscopicNavigation</guiname>\n"
"  <tclinitname>Neuroendoscopicnavigation_Init</tclinitname>\n"
"  <message>Initializing NeuroEndoscopic Navigation Module...</message>\n"
"</loadable>\n"
"\n"
;
}

char*
GetLoadableModuleDescription()
{
  return NeuroEndoscopicNavigationModuleDescription;
}

void*
GetLoadableModuleGUI()
{
  return vtkNeuroEndoscopicNavigationGUI::New ( );
}


void*
GetLoadableModuleLogic()
{
  return vtkNeuroEndoscopicNavigationLogic::New ( );
}
