-useBspline on 
-useBsplineHigh off  

-optimizerType lineSearch    
-imageType normal

-multiLevelAffine 2  
-multiLevelBspline 1  
-multiLevelBsplineHigh 1
 
-optTranslationLearningRate 1e2
-optAffineLearningRate  1e-3
-optBsplineLearningRate 1e2 
-optBsplineHighLearningRate 1e2

-optTranslationNumberOfIterations 50
-optAffineNumberOfIterations 400
-optBsplineNumberOfIterations 500  
-optBsplineHighNumberOfIterations 50 

-numberOfSpatialSamplesTranslation 2000
-numberOfSpatialSamplesAffine 2000
-numberOfSpatialSamplesBspline 5000
-numberOfSpatialSamplesBsplineHigh 5000

-bsplineInitialGridSize 10
-numberOfBsplineLevel 1 
-useBSplineRegularization on 
-bsplineRegularizationFactor 1e0
    
-mask all 
-maskType connectedThreshold 
-threshold1 5 
-threshold2 20

-translationMultiScaleSamplePercentageIncrease 8.0 
-affineMultiScaleSamplePercentageIncrease 8.0 
-bsplineMultiScaleSamplePercentageIncrease 8.0 
    
-translationMultiScaleMaximumIterationIncrease 1.0 
-affineMultiScaleMaximumIterationIncrease 1.0 
-bsplineMultiScaleMaximumIterationIncrease 1.0
  
-translationMultiScaleStepLengthIncrease 1e-1 
-affineMultiScaleStepLengthIncrease 1e-1 
-bsplineMultiScaleStepLengthIncrease 1e-1 
    
-translationScaleCoeffs 1e-4 
-gaussianFilterVariance 3.0 
-maximumLineIteration 10 
-parzenWindowStandardDeviation 0.4
    

