-useBspline on 
-useBsplineHigh off  

-optimizerType lineSearch    
-imageType normal

-multiLevelAffine 2  
-multiLevelBspline 1  
-multiLevelBsplineHigh 1
 
-optTranslationLearningRate 1e5 
-optAffineLearningRate  1e-3 
-optBsplineLearningRate 1e5 
-optBsplineHighLearningRate 1e5
 
-optTranslationNumberOfIterations 50 
-optAffineNumberOfIterations 500  
-optBsplineNumberOfIterations 500  
-optBsplineHighNumberOfIterations 500 

-numberOfSpatialSamplesTranslationPercentage 25e-5 
-numberOfSpatialSamplesAffinePercentage 25e-5 
-numberOfSpatialSamplesBsplinePercentage 5e-4 
-numberOfSpatialSamplesBsplineHighPercentage 1e-3
    
-numberOfSpatialSamplesTranslation 2000
-numberOfSpatialSamplesAffine 2000
-numberOfSpatialSamplesBspline 4000
-numberOfSpatialSamplesBsplineHigh 4000

-bsplineInitialGridSize 5 
-numberOfBsplineLevel 1 
-useBSplineRegularization on 
-bsplineRegularizationFactor 1e-1
    
-mask all 
-maskType connectedThreshold 
-threshold1 8 
-threshold2 20


-translationMultiScaleSamplePercentageIncrease 4.0 
-affineMultiScaleSamplePercentageIncrease 4.0 
-bsplineMultiScaleSamplePercentageIncrease 4.0 
    
-translationMultiScaleMaximumIterationIncrease 1.0 
-affineMultiScaleMaximumIterationIncrease 1.0 
-bsplineMultiScaleMaximumIterationIncrease 1.0
  
-translationMultiScaleStepLengthIncrease 1e-1 
-affineMultiScaleStepLengthIncrease 1e-1 
-bsplineMultiScaleStepLengthIncrease 1e-1 
    
-translationScaleCoeffs 1e-5 
-gaussianFilterVariance 2.0 
-maximumLineIteration 10 
-parzenWindowStandardDeviation 0.4
    

